on:
  workflow_dispatch:
name: Create Release


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }} (can be github.run_number)
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          generate_release_notes: true
